name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Or whichever branch you want to deploy from

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build the site
        run: |
          # Add the steps to build your site here, like running npm or other build commands

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./path-to-your-built-site  # Replace with the correct build folder
